2025-04-28 15:36:44,261 - INFO - Request: GET /admin/dashboard - Status: 200
2025-04-28 15:36:44,456 - INFO - Request: GET /static/js/script.js - Status: 200
2025-04-28 15:36:44,462 - INFO - Request: GET /static/css/style.css - Status: 200
2025-04-28 15:36:44,497 - INFO - Request: GET /static/css/fonts.css - Status: 200
2025-04-28 15:36:44,592 - ERROR - Exception occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-28 15:36:44,594 - INFO - Request: GET /favicon.ico - Status: 500
2025-04-28 15:36:45,833 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:36:45,878 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:45,878 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:45,901 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:47,073 - INFO - Request: GET /admin/dashboard - Status: 200
2025-04-28 15:36:47,160 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:47,162 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:47,200 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:47,949 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:36:48,000 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:48,010 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:48,032 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:51,833 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:36:51,876 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:51,879 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:51,895 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:53,260 - INFO - Request: GET /admin/dashboard - Status: 200
2025-04-28 15:36:53,312 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:53,312 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:53,325 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:53,883 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:36:53,938 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:53,938 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:53,954 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:54,367 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:36:54,400 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:54,400 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:54,421 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:54,854 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:36:54,891 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:54,893 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:54,904 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:55,778 - INFO - Request: GET /admin/dashboard - Status: 200
2025-04-28 15:36:55,856 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:55,856 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:55,925 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:56,594 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:36:56,650 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:56,650 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:56,673 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:59,159 - INFO - Request: GET /admin/backup - Status: 200
2025-04-28 15:36:59,234 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:36:59,234 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:36:59,264 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:36:59,331 - ERROR - Exception occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-28 15:36:59,331 - INFO - Request: GET /favicon.ico - Status: 500
2025-04-28 15:37:00,234 - INFO - Request: GET /admin/pages - Status: 200
2025-04-28 15:37:01,348 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:37:01,391 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:37:01,391 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:37:01,408 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:37:35,153 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:37:35,220 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:37:35,230 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:37:35,253 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:37:37,930 - INFO - Request: GET /admin/dashboard - Status: 200
2025-04-28 15:37:37,994 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:37:37,994 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:37:38,008 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:37:38,041 - ERROR - Exception occurred: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\PythonProject\.venv\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

2025-04-28 15:37:38,043 - INFO - Request: GET /favicon.ico - Status: 500
2025-04-28 15:37:43,424 - INFO - Request: GET /admin/logs - Status: 200
2025-04-28 15:37:43,481 - INFO - Request: GET /static/css/style.css - Status: 304
2025-04-28 15:37:43,481 - INFO - Request: GET /static/js/script.js - Status: 304
2025-04-28 15:37:43,494 - INFO - Request: GET /static/css/fonts.css - Status: 304
2025-04-28 15:38:58,267 - INFO - Request: GET /admin/dashboard - Status: 200
2025-04-28 15:38:58,358 - INFO - Request: GET /static/css/style.css - Status: 200
2025-04-28 15:38:58,359 - INFO - Request: GET /static/js/script.js - Status: 200
2025-04-28 15:38:58,528 - INFO - Request: GET /static/css/fonts.css - Status: 200
